-- ══════════════════════════════════════════════════════════════════════
--  Grow Farms — seed data
--
--  Every row below was extracted from the existing React frontend.
--  Generated by: node src/scripts/generateSql.js
--
--  Prefer `npm run db:seed` — it is idempotent, hashes the admin password
--  with bcrypt at runtime, and can be re-run safely. Use this file only
--  for a raw phpMyAdmin / cPanel import.
--
--  NOTE: the admin password hash below is for 'Admin@12345'
--        (taken from SEED_ADMIN_PASSWORD in .env at generation time).
--        Change it immediately after your first login.
-- ══════════════════════════════════════════════════════════════════════

USE `growfarms`;
SET FOREIGN_KEY_CHECKS = 0;

-- ── admins ──
INSERT INTO `admins` (`id`, `name`, `email`, `password_hash`, `role`, `is_active`, `created_at`, `updated_at`) VALUES
  (1, 'Grow Farms Admin', 'admin@growfarms.com', '$2a$12$11JxVmK8kKcm95vKCtNmp.j7oEcXq4C80n5KEexpp4s/imudVLiRy', 'super_admin', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── categories ──
INSERT INTO `categories` (`id`, `is_active`, `name`, `slug`, `type`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'Farmland Projects', 'farmland-projects', 'project', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'Residential Farmland', 'residential-farmland', 'project', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'Land Packages', 'land-packages', 'package', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, 'Bungalow Packages', 'bungalow-packages', 'package', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, 'Mixed Farming', 'mixed-farming', 'blog', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 1, 'Agriculture', 'agriculture', 'blog', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 1, 'Investment', 'investment', 'blog', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── projects ──
INSERT INTO `projects` (`id`, `category_id`, `slug`, `title`, `short_description`, `full_description`, `location`, `hero_image`, `map_pin_top`, `map_pin_left`, `status`, `is_featured`, `show_on_map`, `sort_order`, `created_at`, `updated_at`, `total_area`, `meta_title`, `meta_description`) VALUES
  (1, 1, 'skybreez', 'Skybreez', 'Serene hillside farmhouse plots with panoramic valley views.', 'Skybreez by Grow Farms is a tranquil farmhouse community nestled in the rolling hills near Mumbai. Designed for those who seek a peaceful escape, each plot offers sweeping valley views, fresh mountain air, and a chance to reconnect with nature — while staying close to city conveniences.', 'Near Mumbai, Maharashtra', 'uploads/seed/home_banner_2.jpg', 78.7, 19.1, 'active', 0, 1, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL),
  (2, 2, 'sarasview', 'Sarasview', 'Premium plots overlooking the rocky peaks and lush canopy.', 'Sarasview by Grow Farms is a sprawling 140-acre residential farmland development located in the peaceful surroundings of Aptavane Village, just 2 km away from the historic Pali city in Maharashtra.', 'Aptavane Village, Pali, Maharashtra', 'uploads/seed/Details_Banner.jpg', 61.1, 49.4, 'active', 1, 1, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', '140 acres', 'Sarasview — 140-acre Residential Farmland near Pali | Grow Farms', 'Scenic river-touch farmland plots at Aptavane Village, 2 km from Pali, Maharashtra. Gated, plotted and ready to own.'),
  (3, 1, 'xyzview', 'Xyzview', 'Premium plots overlooking the rocky peaks and lush canopy.', 'Xyzview offers premium farmland plots with breathtaking views of the surrounding peaks and verdant canopy. A rare opportunity to own land in one of Maharashtra\'s most scenic corridors.', 'Pali, Maharashtra', 'uploads/seed/home_banner_2.jpg', 51.4, 83.8, 'active', 0, 1, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL),
  (4, 1, 'syview-2', 'Syview 2', 'Premium plots overlooking the rocky peaks and lush canopy.', 'Syview 2 expands on the success of our first phase, offering larger plots with enhanced amenities and unobstructed views of the natural landscape.', 'Pali, Maharashtra', 'uploads/seed/home_banner_2.jpg', 78.7, 74.4, 'active', 0, 1, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL);

-- ── project_images ──
INSERT INTO `project_images` (`id`, `project_id`, `image_path`, `alt_text`, `is_primary`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'uploads/seed/home_banner_2.jpg', 'Skybreez', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 2, 'uploads/seed/Details_Banner.jpg', 'Sarasview', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 3, 'uploads/seed/home_banner_2.jpg', 'Xyzview', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 4, 'uploads/seed/home_banner_2.jpg', 'Syview 2', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── packages ──
INSERT INTO `packages` (`id`, `project_id`, `category_id`, `slug`, `title`, `description`, `price`, `price_label`, `area_sqft`, `button_variant`, `button_color`, `button_label`, `card_rotate`, `status`, `sort_order`, `created_at`, `updated_at`, `built_up_sqft`, `configuration`) VALUES
  (1, 2, 3, 'farm-land', 'Farm Land', '21,780 Sq. Ft. Agricultural Land With Basic Plantation, Fencing, Water, Electricity, Road Access, And All Essential Common Amenities.', 599000, '₹5.99 Lakh', 21780, 'outline', '#D4AF37', 'Book Now', -5, 'active', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL),
  (2, 2, 4, 'farmland-with-2bhk-bungalow', 'Farmland With 2BHK Bungalow', '21,780 Sq. Ft. Agricultural Land With An 800 Sq. Ft. 2BHK Bungalow And All Essential Basic Amenities Included.', 1598000, '₹15.98 Lakh', 21780, 'solid', '#D4AF37', 'Book Now', 5, 'active', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', 800, '2BHK');

-- ── package_images ──
INSERT INTO `package_images` (`id`, `package_id`, `image_path`, `alt_text`, `is_primary`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'uploads/seed/Land_Pakages_1.jpg', 'Farm Land', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'uploads/seed/Land_Pakages_1.jpg', 'Farm Land', 0, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'uploads/seed/Land_Pakages_1.jpg', 'Farm Land', 0, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 2, 'uploads/seed/Land_Pakages_2.jpg', 'Farmland With 2BHK Bungalow', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 2, 'uploads/seed/Land_Pakages_2.jpg', 'Farmland With 2BHK Bungalow', 0, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 2, 'uploads/seed/Land_Pakages_2.jpg', 'Farmland With 2BHK Bungalow', 0, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── package_tags ──
INSERT INTO `package_tags` (`id`, `package_id`, `label`, `accent_color`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'Road Access', NULL, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'Fencing', NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, '₹5.99 Lakh', '#D4AF37', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 2, '21,780 Sq. Ft.', NULL, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 2, '2BHK', NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 2, '₹15.98 Lakh', '#4C7A4F', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── amenities ──
INSERT INTO `amenities` (`id`, `is_active`, `name`, `icon_key`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'Water Facility', 'water', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'Electricity', 'electricity', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'Gated Community', 'gated', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, 'Plantation', 'plantation', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, '24x7 Security', 'security', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 1, 'Clear Title', 'title', 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 1, 'Common Garden', 'garden', 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (8, 1, 'Tar Road', 'road', 8, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── project_amenities ──
INSERT INTO `project_amenities` (`id`, `project_id`, `amenity_id`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 2, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 3, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, 4, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, 5, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 1, 6, 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 1, 7, 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (8, 1, 8, 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (9, 2, 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (10, 2, 2, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (11, 2, 3, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (12, 2, 4, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (13, 2, 5, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (14, 2, 6, 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (15, 2, 7, 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (16, 2, 8, 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (17, 3, 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (18, 3, 2, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (19, 3, 3, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (20, 3, 4, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (21, 3, 5, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (22, 3, 6, 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (23, 3, 7, 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (24, 3, 8, 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (25, 4, 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (26, 4, 2, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (27, 4, 3, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (28, 4, 4, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (29, 4, 5, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (30, 4, 6, 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (31, 4, 7, 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (32, 4, 8, 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── facilities ──
INSERT INTO `facilities` (`id`, `project_id`, `is_active`, `name`, `icon_image`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 2, 1, 'Hospital', 'uploads/seed/Hospital.png', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 2, 1, 'School', 'uploads/seed/school.png', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 2, 1, 'College', 'uploads/seed/College.png', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 2, 1, 'Local Market', 'uploads/seed/local_market.png', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 2, 1, 'Highway', 'uploads/seed/Highway.png', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── travel_routes ──
INSERT INTO `travel_routes` (`id`, `project_id`, `is_active`, `mode`, `label`, `icon_image`, `description`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 2, 1, 'road', 'By Road', 'uploads/seed/By_Road.png', 'Pali is approximately 112 kilometers away from Mumbai. You can drive by car or hire a taxi. State transport buses and private buses also operate between Mumbai and Pali.', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 2, 1, 'train', 'By Train', 'uploads/seed/By_Train.png', 'Pali is approximately 112 kilometers away from Mumbai. You can drive by car or hire a taxi. State transport buses and private buses also operate between Mumbai and Pali.', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 2, 1, 'air', 'By Air', 'uploads/seed/By_Air.png', 'Pali is approximately 112 kilometers away from Mumbai. You can drive by car or hire a taxi. State transport buses and private buses also operate between Mumbai and Pali.', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── buying_steps ──
INSERT INTO `buying_steps` (`id`, `is_active`, `default_open`, `rotate`, `scope`, `step_number`, `title`, `description`, `pos_top`, `pos_left`, `width`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 0, 0, 'details', '01', 'Explore Available Plots', 'Browse our curated selection of verified farmland plots across prime agricultural zones suited to your investment goals.', '22%', '57%', 236, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 0, 0, 'details', '02', 'Schedule A Site Visit', 'Book a guided on-site visit with our land experts to experience the property firsthand before making any commitment.', '46%', '32%', 214, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 1, -4, 'details', '03', 'Verify & Complete Documentation', 'Review all legal documents, verify the property details, and complete the purchase process securely.', '70%', '60%', 242, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, 0, 20, 'details', '04', 'Become A Proud Land Owner', 'Complete payment and registration to officially become a proud farmland owner and begin your agricultural journey.', '90%', '30%', 236, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, 0, 0, 'blog', '01', 'Choose Your Plot', 'Explore our premium agricultural land options and select the perfect location.', NULL, NULL, NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 1, 0, 0, 'blog', '02', 'Visit the Site', 'Schedule a site visit with our experts to experience the project firsthand.', NULL, NULL, NULL, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 1, 0, 0, 'blog', '03', 'Complete Your Investment', 'Our team assists you throughout the documentation process, ensuring a smooth and transparent purchase.', NULL, NULL, NULL, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── why_pali_slides ──
INSERT INTO `why_pali_slides` (`id`, `is_active`, `title`, `description`, `image`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'Smart Investment', 'Buying Farm Land In Pali Supports The Local Community. It Can Create Jobs And Help Growth.', 'uploads/seed/Why_Pali_1.png', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'Helps The Local Area', 'Buying Farm Land In Pali Supports The Local Community. It Can Create Jobs And Help Job Growth.', 'uploads/seed/Why_Pali_2.png', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'Sustainable Land', 'Every Acre In Pali Is Farmed Responsibly, Protecting Soil Health For Generations To Come.', 'uploads/seed/Why_Pali_3.png', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, 'Long Term Value', 'Farmland In Pali Has Steadily Appreciated, Making It A Reliable Store Of Value Over Time.', 'uploads/seed/Why_Pali_1.png', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, 'Trusted Partnership', 'Our Local Team Manages Every Plot Directly, So You Invest With Full Transparency.', 'uploads/seed/Why_Pali_2.png', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── why_choose_cards ──
INSERT INTO `why_choose_cards` (`id`, `project_id`, `is_active`, `position`, `title`, `body`, `image`, `alt_text`, `object_position`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 2, 1, 'left', 'History & Culture', 'Buying farm land in Pali supports the community. It can create jobs and strengthen local heritage.', 'uploads/seed/animals.png', 'Animals in Pali farmland', 'center', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 2, 1, 'center', 'Green Environment', 'Pali offers open spaces, cleaner air, and a nature-centric lifestyle without sacrificing convenience.', 'uploads/seed/Why_Pali_1.png', 'Green farm life in Pali', 'center', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 2, 1, 'right', 'Helps The Local Area', 'Buying farm land in Pali supports the local community. It can create jobs and help the local economy.', 'uploads/seed/Why_Pali_2.png', 'Farm workers in Pali', 'center', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── philosophy_cards ──
INSERT INTO `philosophy_cards` (`id`, `is_active`, `title`, `icon_key`, `body`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'Mission', 'mission', 'To build lasting trust with customers and stakeholders through quality products and services. We drive growth and consistency to maintain a leading market reputation.', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'Vision', 'vision', 'Cultivating a future where agricultural investment is accessible, transparent, and environmentally restorative for generations to come.', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'Values', 'values', 'Integrity in every transaction, consistency in our delivery, and an unwavering respect for the land that provides our wealth.', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── faqs ──
INSERT INTO `faqs` (`id`, `is_active`, `project_id`, `question`, `answer`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, NULL, 'Can I use Spline for free?', 'Yes, totally! The Basic plan is free. You can have unlimited personal files and file viewers. Maximum 1 team project can be created with 2 team files and 2 editors. You also have access to the Spline Library and can publish your scenes with a Spline logo.', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, NULL, 'Why should I upgrade to Super or Super Team?', 'Upgrading gives you access to advanced features like custom domains, no Spline branding, unlimited team projects, priority support, and much more to power your professional workflow.', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, NULL, 'What payment methods can I use?', 'We accept all major credit and debit cards (Visa, Mastercard, Amex), as well as PayPal. All payments are securely processed and encrypted.', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, NULL, 'How does team billing work?', 'Team billing is calculated per seat. Each member added to your team will be charged at the same rate as your plan. You\'ll be billed at the start of each billing cycle for the total number of seats.', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, NULL, 'How can I cancel my subscription?', 'You can cancel your subscription at any time from your account settings under Billing. Your plan will remain active until the end of the current billing period.', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 1, NULL, 'Can I change from monthly to yearly?', 'Yes! You can switch from monthly to yearly billing at any time. The switch will take effect at the start of your next billing cycle and you\'ll enjoy a discounted annual rate.', 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 1, NULL, 'How can I ask other questions about pricing?', 'Feel free to reach out to our support team via the in-app chat or email us at support@spline.design. We\'re happy to help with any pricing or billing questions.', 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (8, 1, NULL, 'Interested in Spline for Education?', 'We offer special plans for students and educators. Apply through our Education program page and get access to premium features at no cost or a significantly reduced rate.', 8, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── testimonials ──
INSERT INTO `testimonials` (`id`, `is_active`, `youtube_id`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'fcx0LV7C2pE', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'DxA4B7bJpRk', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'AYSdZFo1Yxw', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, '1xkuNlpQhvc', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 1, 'd8ul6Akvu7o', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 1, 'TJfRcYy5y1M', 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── social_links ──
INSERT INTO `social_links` (`id`, `name`, `platform`, `url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES
  (1, 'Facebook', 'facebook', 'https://www.facebook.com/', 1, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 'Instagram', 'instagram', 'https://www.instagram.com/', 2, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 'YouTube', 'youtube', 'https://www.youtube.com/', 3, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 'X (Twitter)', 'twitter', 'https://x.com/', 4, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 'LinkedIn', 'linkedin', 'https://www.linkedin.com/', 5, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 'WhatsApp', 'whatsapp', 'https://wa.me/', 6, 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── blogs ──
INSERT INTO `blogs` (`id`, `slug`, `category_id`, `views`, `title`, `hero_title`, `hero_subtitle`, `sub_heading`, `second_description`, `content`, `featured_image`, `banner_image`, `author_name`, `published_at`, `status`, `is_featured`, `sort_order`, `quote_text`, `quote_author`, `created_at`, `updated_at`) VALUES
  (1, 'better-agriculture-for-better-future', 5, 0, 'Better Agriculture for Better Future', 'Blog Details', '', 'Everything on our farm is grown', 'They offer adaptability, high nutritional value, and can yield higher yields with minimal agronomic inputs, and provide significant potential for sustainable agriculture and provide nutritional and income security for small and marginal farmers in dry and rainfed semi-arid regions.', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 1, 1, 'When you listen to yourself, everything come naturally. It come from in, like a kind of will to do something. Try to be sensitive. That is just a few clicks away.', 'Satisfied Client', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 'a-farmer-is-a-person-who-works-in-agriculture-1', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 2, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 'a-farmer-is-a-person-who-works-in-agriculture-2', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 3, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 'a-farmer-is-a-person-who-works-in-agriculture-3', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 4, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 'a-farmer-is-a-person-who-works-in-agriculture-4', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 5, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 'a-farmer-is-a-person-who-works-in-agriculture-5', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 6, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 'a-farmer-is-a-person-who-works-in-agriculture-6', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 7, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (8, 'a-farmer-is-a-person-who-works-in-agriculture-7', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 8, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (9, 'a-farmer-is-a-person-who-works-in-agriculture-8', 5, 0, 'A farmer is a person who works in agriculture.', '', '', '', '', '<p>Grow Farms brings you verified, plotted agricultural land near Pali, Maharashtra. Every plot is documented, fenced and serviced with water, electricity and road access.</p><p>Our team walks you through site selection, a guided visit, full legal verification and registration — so owning farmland is as straightforward as it should be.</p>', 'uploads/seed/Blog_Banner_2.jpeg', 'uploads/seed/blog_details.png', 'Admin', '2024-03-28 10:00:00', 'published', 0, 9, '', '', '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── blog_checklist ──
INSERT INTO `blog_checklist` (`id`, `blog_id`, `item_text`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'Make ridges when planting crops on your farm of flat land.', 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'Instantly connects with an Agronomist to remediate', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 1, 'Keep Yourself Current and on top of Latest Farming Trends', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 1, 'Make the earth cleaner, make the earth greener.', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── blog_images ──
INSERT INTO `blog_images` (`id`, `blog_id`, `image_path`, `alt_text`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 1, 'uploads/seed/Blog_Banner_2.jpeg', 'Better Agriculture for Better Future', 0, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 1, 'uploads/seed/Blog_Banner_2.jpeg', 'Better Agriculture for Better Future', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00');

-- ── blog_steps ──

-- ── website_content ──
INSERT INTO `website_content` (`id`, `is_active`, `page`, `section_key`, `label`, `title`, `subtitle`, `sort_order`, `created_at`, `updated_at`, `link_label`, `link_url`, `body`, `image`, `extra_data`) VALUES
  (1, 1, 'home', 'hero_stage_1', 'Hero — scroll stage 1', 'Own a Piece of\nNature, Not Just Land.', 'Premium farmhouse plots designed for peaceful living, smart investment, and future generations.', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (2, 1, 'home', 'hero_stage_2', 'Hero — scroll stage 2', 'Where Serenity Meets\nSmart Investment.', 'Curated land that appreciates over time while giving you a sanctuary away from city chaos.', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (3, 1, 'home', 'hero_stage_3', 'Hero — scroll stage 3', 'Build Memories That\nOutlast Generations.', 'Lush greenery, clean air, and space to breathe — right at your doorstep, near Mumbai.', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (4, 1, 'home', 'testimonial_heading', 'Testimonial section heading', 'Testimonial', 'A place that grows in value while giving peace today.', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00', 'View All', '/testimonials', NULL, NULL, NULL),
  (5, 1, 'about', 'hero', 'About hero', 'Where Nature Meets Smart Investment', 'About GrowFarms', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, 'We help you own premium farmland with complete transparency, expert guidance, and long-term value.', 'uploads/seed/About_Banner.png', NULL),
  (6, 1, 'about', 'trust_section', '15 Years of Cultivating Trust', '15 Years of Cultivating Trust', 'Our Legacy', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, 'Grow Farms has a strong foothold in the market, with 15 years of experience. We guarantee reliable delivery of agricultural land, merging the grit of traditional farming with the precision of modern financial management.', 'uploads/seed/trust_img.jpg', '{\"stats\":[{\"value\":15,\"suffix\":\"+\",\"label\":\"Years Experience\"},{\"value\":7,\"suffix\":\"-8\",\"label\":\"Avg. Team Tenure\"}],\"quote\":\"Our commitment extends beyond transactions; we prioritize environmental and health considerations in every acre we manage.\",\"card_title\":\"Certified Stability\",\"card_text\":\"We understand your dream of a second home surrounded by nature.\"}'),
  (7, 1, 'about', 'philosophy_heading', 'Core Philosophy heading', 'Core Philosophy', NULL, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (8, 1, 'details', 'about_project', 'About the project', 'About Sarasview', NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, 'Sarasview by Grow Farms is a sprawling 140-acre residential farmland development located in the peaceful surroundings of Aptavane Village, just 2 km away from the historic Pali city in Maharashtra. This project provides an ideal opportunity for nature lovers and investors alike to own a piece of pristine land. It offers scenic river-touch plots, making it a perfect retreat for those who seek tranquility, yet desire modern conveniences.', 'uploads/seed/About_Img_1.png', NULL),
  (9, 1, 'details', 'facilities_heading', 'Local Facilities heading', 'Local Facilities', NULL, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (10, 1, 'details', 'invest_in_pali', 'Why should invest in Pali', 'Why should invest in Pali', NULL, 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, 'uploads/seed/newlandscapeimg.png', NULL),
  (11, 1, 'details', 'amenities_heading', 'Amenities heading', 'Amenities', NULL, 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (12, 1, 'details', 'packages_heading', 'Land Packages heading', 'Land Packages', 'Offerings', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (13, 1, 'details', 'why_pali_heading', 'Why Pali heading', 'Why Pali?', NULL, 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (14, 1, 'blogs', 'detail_hero', 'Article hero', 'Blog Details', NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', 'All blogs', NULL, NULL, NULL, NULL),
  (15, 1, 'blogs', 'detail_related', 'Other Blog heading', 'Other Blog', NULL, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, NULL),
  (16, 1, 'contact', 'hero', 'Contact hero', 'Contact Us', NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, 'uploads/seed/Contact_banner.png', NULL),
  (17, 1, 'contact', 'info_cards', 'Contact info cards', NULL, NULL, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, '{\"cards\":[{\"icon\":\"mail\",\"title\":\"Mail us 24/7\",\"lines\":[\"pbminfo@admin.com\",\"pbmadmin@info.com\"],\"link\":\"\"},{\"icon\":\"phone\",\"title\":\"Call us 24/7\",\"lines\":[\"Phone : (+55) 654 - 545 - 5418\",\"Mobile : (+01) 654 - 545 - 1235\"],\"link\":\"\"},{\"icon\":\"map\",\"title\":\"Our Locations\",\"lines\":[\"4821 Ride Top, Anch St, Alaska\",\"997998, USA main city.\"],\"link\":\"\"}]}'),
  (18, 1, 'global', 'footer', 'Footer', 'GROW FARMS', NULL, 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, 'Grow Farms 305, The Landmark, Next to Hotel Three Star, Sector 7, Kharghar, Navi Mumbai, Maharashtra 410210', NULL, '{\"navigation\":[{\"label\":\"Home\",\"url\":\"/\"},{\"label\":\"About us\",\"url\":\"/about\"},{\"label\":\"Testimonials\",\"url\":\"/testimonials\"},{\"label\":\"Blog\",\"url\":\"/blogs\"}],\"projects\":[{\"label\":\"Sky Breeze\",\"url\":\"/details/skybreez\"},{\"label\":\"Sarasview\",\"url\":\"/details/sarasview\"}],\"copyright\":\"©2026 Grow Farms. All rights reserved.\"}'),
  (19, 1, 'global', 'navigation', 'Main navigation', NULL, NULL, 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00', NULL, NULL, NULL, NULL, '{\"items\":[{\"name\":\"Home\",\"path\":\"/\"},{\"name\":\"About Us\",\"path\":\"/about\"},{\"name\":\"Blogs\",\"path\":\"/blogs\"},{\"name\":\"Contact Us\",\"path\":\"/contact\"}]}');

-- ── settings ──
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `label`, `setting_group`, `setting_type`, `sort_order`, `created_at`, `updated_at`) VALUES
  (1, 'site_name', 'Grow Farms', 'Site name', 'general', 'text', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (2, 'site_tagline', 'Own a Piece of Nature, Not Just Land.', 'Tagline', 'general', 'text', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (3, 'site_logo', 'uploads/seed/grow-farms-logo.png', 'Logo', 'media', 'image', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (4, 'site_favicon', 'uploads/seed/logo_1.png', 'Favicon', 'media', 'image', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (5, 'contact_email_1', 'pbminfo@admin.com', 'Primary email', 'contact', 'email', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (6, 'contact_email_2', 'pbmadmin@info.com', 'Secondary email', 'contact', 'email', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (7, 'contact_phone_1', '(+55) 654 - 545 - 5418', 'Phone', 'contact', 'text', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (8, 'contact_phone_2', '(+01) 654 - 545 - 1235', 'Mobile', 'contact', 'text', 4, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (9, 'contact_address', 'Grow Farms 305, The Landmark, Next to Hotel Three Star, Sector 7, Kharghar, Navi Mumbai, Maharashtra 410210', 'Office address', 'contact', 'textarea', 5, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (10, 'google_map_embed', 'https://www.google.com/maps?q=Mumbai,Maharashtra,India&output=embed', 'Google Maps embed URL', 'contact', 'url', 6, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (11, 'google_map_link', 'https://www.google.com/maps?q=Mumbai,Maharashtra,India', 'Google Maps link (opens in a new tab)', 'contact', 'url', 7, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (12, 'meta_title', 'Grow Farm', 'Default meta title', 'seo', 'text', 1, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (13, 'meta_description', 'Premium farmhouse plots near Pali, Maharashtra — designed for peaceful living, smart investment, and future generations.', 'Default meta description', 'seo', 'textarea', 2, '2026-09-02 12:00:00', '2026-09-02 12:00:00'),
  (14, 'copyright_text', '©2026 Grow Farms. All rights reserved.', 'Copyright line', 'general', 'text', 3, '2026-09-02 12:00:00', '2026-09-02 12:00:00');


SET FOREIGN_KEY_CHECKS = 1;
